server:
  port: 8094

spring:
  # 数据库配置；启动时配置数据库资源信息
  datasource:
    mysql:
      username:
      password:
      url: jdbc:mysql:///chat-platform-plus?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: MainHikariPool
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
    pgvector:
      username:
      password:
      url:
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 25
        minimum-idle: 15
        idle-timeout: 180000
        connection-timeout: 30000

  ai:
    ollama:
      base-url:
      embedding:
        options:
          num-batch: 512
        model: nomic-embed-text

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtps
    username:
    password:
    application_name:

  # 上传文件大小限制
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  # RabbitMQ
  rabbitmq:
    addresses:
    port:
    username:
    password:
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    template:
      delivery-mode: persistent # 确保全局默认设置为持久化（可选）
    # 消息配置
    config:
      # 生产者
      producer:
        exchange: chat_platform_plus_exchange
        topic_order_pay_success:
          topic: topic.order_pay_success
          queue: chat_platform_plus_order_pay_success_queue
      # 消费者
      consumer:
        topic_team_success:
          exchange: groupbuy_market_plus_exchange
          routing_key: topic.team_success
          queue: groupbuy_market_plus_topic_team_success_queue

        topic_order_pay_success:
          exchange: chat_platform_plus_exchange
          routing_key: topic.order_pay_success
          queue: chat_platform_plus_order_pay_success_queue

# MyBatis 配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Redis
redis:
  sdk:
    config:
      host:
      port:
      password:
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# Http客户端配置
okhttpclient:
  config:
    connectTimeOut: 60
    writeTimeOut: 60
    readTimeOut: 60

# 通义千问配置
qwen:
  sdk:
    config:
      enable: true
      api-key:

# 阿里云OSS配置
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:

# Satoken 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# GitHub
github:
  username:
  token:

# 蓝兔支付
ltzf:
  sdk:
    config:
      app_id:      # 应用者 Id
      mch_id:      # 商户号
      partner_key: # 密钥
      notify_url:

# 拼团营销服务
app:
  config:
    groupbuy-market-plus:
      api_url:
      notify_url:
      source: s01
      channel: c01

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml